### ISSUE TITLE
Change copyright text

### ISSUE THREAD

**Issue by EstherBoere** [iiasa/COACCH#1]
Either remove (preferred) or change the copyright notification.
Not sure if it needs a Copyright as all the individual files already have a license and it should be distributed under an open license.

If we do need one, then change to "Copyright 2021, IIASA"

**Comment by hvalin** [comment]
I changed the file in conf.py. I suppose next time we rebuild the page, the copyright will now display "IIASA".

**Comment by acjbrouwer** [comment]
Good find @hvalin, but wrong supposition: the rebuild was automatic after you made the change. See [here](https://github.com/iiasa/COACCH/actions).
