### ISSUE TITLE
Index further metadata

### ISSUE THREAD

**Issue by acjbrouwer** [iiasa/COACCH#10]
The COACCH-specific metadata has, beyond the **Keywords** element, further elements that could be used to build the index. Potentially:
- **Partner**
- **Model type/method**
- **Model**
- **Sector**

Try to enrich the index with these.

**Comment by EstherBoere** [comment]
Thanks very much, I think this ticket can be closed?

**Comment by acjbrouwer** [comment]
The involved functionality was already more or less added in earlier days, but on account of some tooling and Zenodo hiccups, regeneration of the site/index succeeded only just now. The new index can be seen here:

https://iiasa.github.io/COACCH/en/master/genindex.html

Click on the refresh button in your browser to make sure to get the latest. When unhappy, repopen this issue.

**Comment by acjbrouwer** [comment]
There is an issue with the regeneration: it did not pick up the new datasets.

**Comment by EstherBoere** [comment]
In case unclear, these are the DOIs:
10.5281/zenodo.5703656
10.5281/zenodo.5703659
10.5281/zenodo.5703667

**Comment by acjbrouwer** [comment]
The query does not pick them up:
```
URL: https://zenodo.org/api/records/?sort=-mostrecent&q=&communities=coacch-co-designing-the-assessment-of-climate-change-costs-h2020-project&type=dataset&page=2&size=10
Query resulted in a total of 13 hits with Zenodo IDs:
[4733499,
 5513871,
 5529732,
 5529888,
 5530146,
 5530237,
 5534190,
 5541327,
 5541894,
 5541337,
 5546248,
 5546264,
 5549953]
```

**Comment by EstherBoere** [comment]
Is this something I should work on or is this a technical issue? On my side it seems I have quite some issues accessing Zenodo.

**Comment by acjbrouwer** [comment]
There appears to be an outage of the main site https://zenodo.org but the query REST API is still operable.

**Comment by acjbrouwer** [comment]
Well, with some retries the query worked. So it's indeed a Zenodo-side issue.
