### ISSUE TITLE
Removal of under construction logo

### ISSUE THREAD

**Issue by EstherBoere** [iiasa/COACCH#7]
Dear Albert,

As the changes to be done will likely not be so big anymore, could you remove the 'under construction' logo?
I thought that instead we could add a sentence like: 'Additional datasets will be released upon their finalization within the project'

**Comment by EstherBoere** [comment]
Dear Albert,

Could you please remove the 'under construction' logo?
I thought that instead we could add a sentence like: 'Additional datasets will be released upon their finalization within the project'.
Sorry, it seems that I didn't assign this ticket before. It's quite urgent now though as I have to present the data repository on Wednesday.

**Comment by acjbrouwer** [comment]
Sorry, I did not notice this one until I received notification when the issue was assigned to me. Resolved in commit 02fc36dc72fba89846ca73084265fad3633b490d.
